# Generated by Django 3.1.4 on 2020-12-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ingredients', models.JSONField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
