# Generated by Django 3.1.4 on 2021-01-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCredentials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('houseNumber', models.CharField(max_length=255)),
                ('flatNumber', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('realized', models.IntegerField()),
                ('credentials', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.ordercredentials')),
                ('dishes', models.ManyToManyField(to='pizza_app.Dish')),
            ],
        ),
    ]
