# Generated by Django 3.1.4 on 2021-01-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_auto_20210101_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCredentials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('surname', models.CharField(max_length=255, unique=True)),
                ('street', models.CharField(max_length=255, unique=True)),
                ('houseNumber', models.CharField(max_length=255, unique=True)),
                ('flatNumber', models.CharField(max_length=255, unique=True)),
                ('phoneNumber', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isRealized', models.BooleanField()),
                ('credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.ordercredentials')),
                ('dishes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.dish')),
            ],
        ),
    ]
