# Generated by Django 3.1.4 on 2021-01-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_auto_20210106_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isRealized',
            new_name='realized',
        ),
    ]
